on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🧹 Clean up old dependencies
      run: |
        rm -rf vendor composer.lock

    - name: 📦 Install Composer Dependencies
      run: |
        composer install --no-dev --no-cache --no-scripts

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37334546
        password: ${{ secrets.ftp_password }}
        local-dir: ./  # Diretório local onde os arquivos estão
        server-dir: /htdocs/  # Diretório no servidor FTP onde os arquivos devem ser enviados
        only-new: true  # Adiciona essa linha para enviar apenas arquivos novos
